# Generated by Django 6.1 on 2026-08-27 11:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('status_accreditation', models.CharField(choices=[('Accreditate', 'Аккредитован'), ('Noaccreditate', 'Неаккредитован')], default='Noaccreditate', max_length=20)),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'db_table': 'contractor',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Admin', 'Администратор'), ('Contractor', 'Подрядчик'), ('Manager', 'Менеджер'), ('Security', 'Охранник КПП')], default='Contractor', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Insurance', 'Страхование'), ('Registry', 'СРО')], max_length=20)),
                ('release_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('file', models.FileField(upload_to='compliance_documents')),
                ('id_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot.contractor')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'compliance_document',
            },
        ),
        migrations.CreateModel(
            name='ContractorEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('passport', models.CharField(max_length=11)),
                ('id_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot.contractor')),
            ],
            options={
                'verbose_name': 'Сотрудник подрядчика',
                'verbose_name_plural': 'Сотрудники подрядчиков',
                'db_table': 'contractor_employee',
            },
        ),
        migrations.CreateModel(
            name='AccessPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('permanent', 'Постоянный'), ('temporary', 'Временный'), ('one_time', 'Разовый')], default='temporary', max_length=20)),
                ('zona_access', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('passive', 'Неактивен')], default='active', max_length=20)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot.contractoremployee')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуска',
                'db_table': 'access_pass',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Yurlico', 'Юрлицо'), ('Fizlico', 'Физлицо')], max_length=20, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(help_text='ID Contractor (юрлицо) или ID ContractorEmployee (физлицо)', max_length=36, verbose_name='ID сущности')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата внесения')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Запись черного списка',
                'verbose_name_plural': 'Черный список',
                'db_table': 'blacklist',
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
