# Generated by Django 6.1 on 2026-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='inn',
            field=models.IntegerField(max_length=12),
        ),
    ]
