# Generated by Django 6.1 on 2026-09-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractoremployee',
            old_name='last_name',
            new_name='patronymic',
        ),
    ]
