# Generated by Django 6.1 on 2026-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_rename_last_name_contractoremployee_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractoremployee',
            name='name',
        ),
        migrations.AddField(
            model_name='contractoremployee',
            name='last_name',
            field=models.CharField(default=1, max_length=120, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
